# fly.toml app configuration file generated for bill-split-nextjs on 2025-09-21T20:17:51-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bill-split-nextjs'
primary_region = 'dfw'

[build]

[env]
  PORT = '3050'

[http_service]
  internal_port = 3050
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
